# Generated by Django 5.2.5 on 2025-08-10 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('state', '0002_remove_state_created_at_remove_state_updated_at'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='state',
            name='unique_state_acronym',
        ),
        migrations.AlterUniqueTogether(
            name='state',
            unique_together=set(),
        ),
    ]
