# Generated by Django 5.2.5 on 2025-08-09 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=8, null=True, unique=True)),
                ('social_name', models.CharField(max_length=255, null=True)),
                ('juridical_nature', models.CharField(max_length=4, null=True)),
                ('responsible_qualification', models.CharField(max_length=2, null=True)),
                ('social_capital', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('company_size', models.CharField(max_length=2, null=True)),
                ('federative_entity', models.CharField(max_length=4, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'db_table': 'company',
                'ordering': ['social_name'],
                'constraints': [models.UniqueConstraint(fields=('cnpj',), name='unique_cnpj')],
                'unique_together': {('cnpj',)},
            },
        ),
    ]
