# Generated by Django 5.2.5 on 2025-08-08 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('city', '0001_initial'),
        ('district', '0001_initial'),
        ('state', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=8, unique=True)),
                ('social_name', models.CharField(max_length=255)),
                ('juridical_nature', models.CharField(max_length=4)),
                ('responsible_qualification', models.CharField(max_length=2)),
                ('social_capital', models.DecimalField(decimal_places=2, max_digits=15)),
                ('company_size', models.CharField(max_length=2)),
                ('federative_entity', models.CharField(max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='city.city')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='district.district')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='state.state')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'db_table': 'company',
                'ordering': ['social_name'],
                'constraints': [models.UniqueConstraint(fields=('cnpj',), name='unique_cnpj')],
                'unique_together': {('cnpj',)},
            },
        ),
    ]
