# Generated by Django 5.2.5 on 2025-08-09 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_remove_company_created_at_remove_company_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='juridical_nature',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
