# Generated by Django 5.2.5 on 2025-08-09 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_company_juridical_nature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='federative_entity',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='juridical_nature',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
