# Generated by Django 5.2.5 on 2025-09-17 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_alter_company_federative_entity_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['social_name'], name='company_social_name_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['cnpj'], name='company_cnpj_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['federative_entity'], name='company_federative_entity_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['social_capital'], name='company_social_capital_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['company_size'], name='company_company_size_idx'),
        ),
    ]
