# Generated by Django 5.2.5 on 2025-08-10 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0002_remove_city_created_at_remove_city_updated_at'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='city',
            name='unique_city_state',
        ),
        migrations.AlterUniqueTogether(
            name='city',
            unique_together=set(),
        ),
    ]
