# Generated by Django 5.2.5 on 2025-08-10 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('district', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='district',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='district',
            name='updated_at',
        ),
    ]
