# Generated by Django 5.2.5 on 2025-08-10 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('district', '0002_remove_district_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='district',
            name='unique_district_city',
        ),
        migrations.AlterUniqueTogether(
            name='district',
            unique_together=set(),
        ),
    ]
